name: photoducer
description: Photograph transducer

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.13+13

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  busy_model: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  file_picker: 1.1.1

  flutter:
    sdk: flutter

  flutter_colorpicker: any

  flutter_crashlytics:
    path: ./flutter_crashlytics

  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git

  image: ^2.0.7

  image_picker_saver: 0.1.0

  path_provider: 0.4.1

  persistent_canvas:
    path: ./persistent_canvas

  photo_view: ^0.2.1

  scoped_model: ^1.0.1

  tflite:
    path: ./flutter_tflite


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/dogandhorse.jpg
    - assets/shoeedges.png
    - assets/edges2shoes.tflite
    - assets/edges2shoes.txt
    - assets/contours2cats.tflite
    - assets/contours2cats.txt
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
